spring:
  profiles.active: test
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
auth:
  jwt:
    secret-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    expire-length: 3600000

---

spring.config.activate.on-profile: prod
auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expire-length: ${JWT_VALIDITY}

---

spring.config.activate.on-profile: dev

---

spring.config.activate.on-profile: test
