spring:
  profiles.active: test
  mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER

---

spring.config.activate.on-profile: prod
auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expire-length: ${JWT_VALIDITY}
  kakao:
    clientId: ${KAKAO_CLIENT_ID}
    redirectURI: ${KAKAO_REDIRECT_URI}

---

spring.config.activate.on-profile: dev
auth:
  jwt:
    secret-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    expire-length: 3600000
  kakao:
    clientId: ${KAKAO_CLIENT_ID}
    redirectURI: ${KAKAO_REDIRECT_URI}

---

spring.config.activate.on-profile: test
auth:
  jwt:
    secret-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    expire-length: 3600000
  kakao:
    clientId: 1234567890abcdefghijklmnop
    redirectURI: http://localhost:8080/redirect
