spring:
  profiles.active: test
  mvc:
    pathmatch.matching-strategy: ANT_PATH_MATCHER
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;MODE=MYSQL;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:
auth:
  jwt:
    secret-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    expire-length: 3600000
location:
  validation-limit: 500

---

spring:
  config.activate.on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_URL}:3306/${MYSQL_DB}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expire-length: ${JWT_VALIDITY}
location:
  validation-limit: ${LOCATION_VALIDATION_LIMIT}

---

spring:
  config.activate.on-profile: dev
auth:
  jwt:
    expire-length: ${JWT_VALIDITY}

---

spring:
  config.activate.on-profile: test
