spring:
  profiles.active: test
  mvc:
    pathmatch.matching-strategy: ANT_PATH_MATCHER
  redis:
    host: localhost
    port: 6379
auth:
  jwt:
    secret-key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    expire-length: 3600000
location:
  validation-limit: ${LOCATION_VALIDATION_LIMIT}

---

spring.config.activate.on-profile: prod
auth:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expire-length: ${JWT_VALIDITY}

---

spring.config.activate.on-profile: dev

---

spring.config.activate.on-profile: test
location:
  validation-limit: 500
