name: Test

on:
  push:
    branches:
      - '*'
      - '!master' # remove duplciate

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    environment: prod # where secrets are stored
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Test & Build with 'test' profile
        run: ./gradlew build
